### ISSUE TITLE
Add predict_proba

### ISSUE THREAD

**Issue by rmontanana** [Doctorado-ML/STree#12]
As predict_proba was developed to the binary case, it can be extrapolated to the multiclass case.

**Comment by tallesbrito** [comment]
Hi,

I'm currently doing research applying oblique decision trees. I've found your implementation very helpful but for my problem I must get as result class probabilities instead of predicted class output from the tree.

Is this _predict_proba_ method implementation available in _predicted_proba_ branch working? I mean, is it a tested feature? I ask it because this feature is not currently merged with master branch.

Thank you in advance.

**Comment by rmontanana** [comment]
> Hi,
> 
> I'm currently doing research applying oblique decision trees. I've found your implementation very helpful but for my problem I must get as result class probabilities instead of predicted class output from the tree.
> 
> Is this _predict_proba_ method implementation available in _predicted_proba_ branch working? I mean, is it a tested feature? I ask it because this feature is not currently merged with master branch.
> 

Well in fact is an abandoned feature, it was working when it was a binary classifier but when I moved to multi-class I decided to leave it behind because I didn't need it for my research and was needing a lot of efforts to adapt to multi-class. 

> Thank you in advance.

Thanks for your interest

You may find something useful here:
[calibrated-classification-model-in-scikit-learn](https://machinelearningmastery.com/calibrated-classification-model-in-scikit-learn/
)

**Comment by rmontanana** [comment]
Instead of a SVM point of view it is possible to use a DecisionTree approach, and use this sklearn code:

```python
proba = self.tree_.predict(X)
proba = proba[:, : self.n_classes_]
normalizer = proba.sum(axis=1)[:, np.newaxis]
normalizer[normalizer == 0.0] = 1.0
proba /= normalizer
return proba
```
